 -- Exercise 1 : Items and customers
 -- All items, ordered by price (lowest to highest).
 -- SELECT item, item_price FROM items
 -- ORDER BY item_price ASC;
 -- Items with a price above 80 (80 included), ordered by price (highest to lowest).
-- SELECT item, item_price FROM items
-- WHERE item_price > 80
-- ORDER BY item_price DESC;
-- The first 3 customers in alphabetical order of the first name (A-Z) – exclude the primary key column from the results.
-- SELECT * FROM customers
-- SELECT customer_name,customer_surname FROM customers
-- WHERE customer_id <= 3
-- ORDER BY customer_surname ASC;
-- All last names (no other columns!), in reverse alphabetical order (Z-A)
-- SELECT * FROM customers
-- SELECT DISTINCT customer_surname FROM customers
-- ORDER BY customer_surname DESC;
